services:
  kanban_service:
    container_name: kanban_service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: kanban_be_postgres
    depends_on:
      - kanban_be_postgres

  kanban_be_postgres:
    container_name: kanban_be_postgres
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanban-be
      POSTGRES_PASSWORD: Selaludia1
      POSTGRES_DB: kanban-be