### Get all Task
GET http://localhost:3000/v1/tasks/
Content-Type: application/json
Accept: application/json

### Create Task
POST http://localhost:3000/v1/tasks/
Content-Type: application/json
Accept: application/json

{
  "title": "new task 2",
  "description": "this is new task two"
}

### Get task by id
GET http://localhost:3000/v1/tasks/979746fd-faf8-43cb-9166-b0de072fa7dd
Content-Type: application/json
Accept: application/json

### Update task
PATCH http://localhost:3000/v1/tasks/979746fd-faf8-43cb-9166-b0de072fa7dd
Content-Type: application/json
Accept: application/json

{
  "title": "new task 4 update",
  "status": "DONE"
}

### Delete task
DELETE  http://localhost:3000/v1/tasks/979746fd-faf8-43cb-9166-b0de072fa7dd
Content-Type: application/json
Accept: application/json