### create/register user
POST http://18.140.56.142/users/register/
Content-Type: application/json
Accept: application/json

{
  "name": "Alex Bizzer",
  "email": "all@gmail.com",
  "password": "Selaluapace1"
}

### login user
POST http://18.140.56.142/users/login/
Content-Type: application/json
Accept: application/json

{
  "email": "all@gmail.com",
  "password": "Selaluapace1"
}